// import ableBodies from "./credits/able-bodies.jpg";
// import absentSounds from "./credits/absent-sounds.jpg";

export const credits = [
  {
    id: "able-bodies",
    title: "Able Bodies",
    artist: "From Indian Lakes",
    img: "https://img.discogs.com/wZBas9S9hFyESe-LD4tgyin0ZeA=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6269743-1415226202-4619.jpeg.jpg",
    credits: "Production, Engineering, Mixing, Mastering",
  },
  {
    id: "the-man-with-wooden-legs",
    title: "The Man With Wooden Legs",
    artist: "From Indian Lakes",
    img: "https://img.discogs.com/eVN3i5gnUHZsDOH1j2PCODryKQ0=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7489258-1442521538-5901.jpeg.jpg",
    credits: "Production, Engineering, Mixing, Mastering",
  },
  {
    id: "absent-sounds",
    title: "Absent Sounds",
    artist: "From Indian Lakes",
    img: "https://img.discogs.com/AIjpUFyesz3Rkhdk2v-OjzcdwYs=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6173680-1412902490-8823.jpeg.jpg",
    credits: "Production, Engineering, Mixing",
  },
  {
    id: "artificial-selection",
    title: "Artificial Selection",
    artist: "Dance Gavin Dance",
    img: "https://img.discogs.com/UPjF4Cz2Onk4AwmDDQpbBntoQjI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12110238-1528504698-7153.jpeg.jpg",
    credits: "Mixing/Bass and Various Production",
  },
  {
    id: "summertime-gladness",
    title: "Summertime Gladness",
    artist: "Dance Gavin Dance",
    img: "https://img.discogs.com/cJgKOI4k2yfQ5vFzCxWZp2jbw2g=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10520612-1499128671-1519.jpeg.jpg",
    credits: "Production, Engineering, Mixing, Mastering",
  },
  {
    id: "semi-charmed-life",
    title: "Semi-Charmed Life",
    artist: "Dance Gavin Dance",
    img: "https://img.discogs.com/OAUNnoQy6m5YZ-OdtdYdwuFgJDg=/fit-in/600x598/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12792916-1590933538-1783.jpeg.jpg",
    credits: "Production, Engineering, Mixing",
  },
  {
    id: "stay-lost",
    title: "Stay Lost",
    artist: "Sianvar",
    img: "https://img.discogs.com/0CbasMC6FfwBr1mzM48sfeszRWs=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8963451-1472350394-6147.jpeg.jpg",
    credits: "Production, Engineering, Mixing",
  },
  {
    id: "divisi",
    title: "DIVISI",
    artist: "A Lot Like Birds",
    img: "https://img.discogs.com/ehAGc0A6At0B6W1gB1TVdDDHtes=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10271459-1494450785-6102.jpeg.jpg",
    credits: "Production, Engineering, Mixing",
  },
  {
    id: "these-hands",
    title: "These Hands",
    artist: "Hearts Like Lions",
    img: "https://img.discogs.com/ufl4egQvFTJbvqb828pncniDAts=/fit-in/220x220/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10275290-1494516736-8590.png.jpg",
    credits: "Production, Engineering, Mixing, Mastering",
  },
  {
    id: "if-i-never-speak-again",
    title: "If I Never Speak Again",
    artist: "Hearts Like Lions",
    img: "https://img.discogs.com/hTd2HcUBnSnn7BUXnCgaOAF-YM8=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9916206-1488488031-5306.jpeg.jpg",
    credits: "Production, Engineering, Mixing",
  },
  {
    id: "secret-wars",
    title: "Secret Wars",
    artist: "Hail the Sun",
    img: "https://img.discogs.com/4WXBmPwckATeVApyovQhw-98tNs=/fit-in/550x550/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-11313060-1513990737-9935.jpeg.jpg",
    credits: "Production, Engineering, Mixing, Mastering",
  },
  {
    id: "mental-knife",
    title: "Mental Knife",
    artist: "Hail the Sun",
    img: "https://img.discogs.com/goVYheZyME-Iz4wWeej93nrDcYk=/fit-in/550x550/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12590496-1538184433-2641.jpeg.jpg",
    credits: "Mastering",
  },
  {
    id: "to-speak-to-listen",
    title: "To Speak, To Listen",
    artist: "Eidola",
    img: "https://img.discogs.com/pZDAG6DCDqAoh5At6PCc2s9wQQI=/fit-in/600x621/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10520977-1499139431-7000.jpeg.jpg",
    credits: "Production, Engineering, Mixing, Mastering",
  },
];
